"""Init

Revision ID: bafdcf074112
Revises: c0422d2da7b7
Create Date: 2023-09-22 17:00:26.363950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bafdcf074112'
down_revision: Union[str, None] = 'c0422d2da7b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_contacts_id', table_name='contacts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_contacts_id', 'contacts', ['id'], unique=False)
    # ### end Alembic commands ###
